Kare/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from django.views.generic import TemplateView

from thoughts import urls as thought_urls
from users import urls as user_urls
from groups import urls as group_urls
from users.serializers import router as user_router

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(user_urls, namespace='users')),
    url(r'^thoughts/', include(thought_urls, namespace='thoughts')),
    url(r'^groups/', include(group_urls, namespace='groups')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^api/', include(user_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url('^', include('django.contrib.auth.urls')),
]

thoughts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


CONDITIONS = (
    (0,  'Ecstatic'),
    (5,   'Passionate'),
    (10, 'Happy'),
    (15, 'Optimistic'),
    (20, 'Content'),
    (25, 'Bored'),
    (26 , 'Tierd'),
    (27, 'Hungry'),
    (30, 'Pessimistic'),
    (35, 'Frustrated'),
    (40, 'Overwhelment'),
    (45, 'Disappointment'),
    (50, 'Worried'),
    (55, 'Angry'),
    (60, 'Jealous'),
    (65, 'Insecure '),
    (70, 'Guilty'),
    (75, 'Fear'),
    (80, 'Grief'),
    (85, 'Despair'),
    (90, 'Paranoid'),

)


class Thought(models.Model):
    user = models.ForeignKey(User, related_name='thoughts')
    recorded_at = models. DateTimeField(default = timezone.now, editable = False)
    condition = models.IntegerField(choices = CONDITIONS)
    notes = models.TextField(blank=True, default='')

    def __str__(self):
        return '{} :{}' .format(self.recorded_at.strftime('%Y-%m-%d %H:%M'), self.get_condition_display())

    class Meta:
        ordering = ['-recorded_at']    

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LogoutForm(forms.Form):
    pass


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2')

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms


class Dashboard(
    LoginRequiredMixin,
    SelectRelatedMixin,
    generic.DetailView
):
    model = User
    select_related = ('thoughts',)
    template_name = 'users/dashboard.html'

    def get_object(self, queryset=None):
        return self.request.user


class LogoutView(LoginRequiredMixin, generic.FormView):
    form_class = forms.LogoutForm
    template_name = 'users/logout.html'

    def form_valid(self, form):
        logout(self.request)
        return HttpResponseRedirect(reverse('home'))


class SignUpView(generic.CreateView):
    form_class = forms.SignUpForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('users:dashboard')

users/templates/users/dashboard.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load thought_tags %}

{% block title %}Dashboard | {{ block.super }}{% endblock %}
<style>
   body{
       padding-top: 100px;
   }
    ul > li > a:active{
        color:white;
    }
</style>
{% block content %}
<div class="container new" id="dm">
    <div class="row">
        <div class="col-md-6">
            <h2> &nbsp; </h2>
            <h2>Recent Thoughts</h2>
            <div class="list-group">
                {% for thought in user.thoughts.all %}
                    <div class="list-group-item">
                        <h4 class="list-group-item-heading">
                            <time class="pull-right small" datetime="{{ thought.recorded_at }}">{{ thought.recorded_at|date:"SHORT_DATE_FORMAT" }}</time>
                            {{ thought.get_condition_display }}
                        </h4>
                        {% if thought.notes %} {{ thought.notes|linebreaks }} {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6">
            <h2> &nbsp; </h2>
            {% thought_form %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="ct-chart ct-perfect-fourth"></div>
        </div>
        <div class="col-md-6">
            <h3>Companies</h3>
            <div class="list-group">
                {% for company in user.companies.all %}
                    <a href="{% url 'groups:companies:detail' slug=company.slug %}" class="list-group-item">{{ company.name }}</a>
                {% endfor %}
            </div>

        <h3>Families</h3>
            <div class="list-group">
                {% for family in user.families.all %}
                    <a href="{% url 'groups:families:detail' slug=family.slug %}" class="list-group-item">{{ family.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'js/chartist/chartist.min.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'js/stretchy.js' %}" data-filter="#id_notes" async></script>
    <script src="{% static 'js/chartist/chartist.min.js' %}"></script>
    <script>
        {% chart_data as data %}
        var data = {{ data|safe }};
        new Chartist.Line('.ct-chart', data);
    </script>
{% endblock %}

users/templates/users/logout.html
{% extends "layout.html" %}

{% block title %}Logout | {{ block.super }}{% endblock %}

{% block content %}
<style type="text/css">
	.pt{
		padding-top: 45px;
	}

</style>
<div class="container pt">
    <div class="row">
        <div class="col-md-6">
            <h3>You sure?</h3>
            <form method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Logout" class="btn btn-default">
            </form>
        </div>
        <div class="col-md-6">
            <h3>Come back soon!</h3>
            <p>This site works best if you use it often!</p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/signup.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block title %}Sign Up | {{ block.super }}{% endblock %}

{% block content %}
<style type="text/css">
  .ct{
    padding-top: 50px;
  }
</style>

<div class="container pt">
    <div class="row">
        <div class="col-md-6 ct">
            <h3>Sign Up</h3>
            <form action="" method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                <input type="submit" value="Sign Up" class="btn btn-primary">
            </form>
        </div>
        <div class="col-md-6 ct">
            <h3>Record how you're feeling!</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque delectus, doloremque ducimus fugiat reprehenderit rerum voluptatem! Beatae cumque cupiditate exercitationem facere harum labore quam? Officiis pariatur perspiciatis quam qui vero.</p>
        </div>
    </div>
</div>
{% endblock %}