Kare/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from django.views.generic import TemplateView

from thoughts import urls as thought_urls
from users import urls as user_urls
from groups import urls as group_urls
from users.serializers import router as user_router

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(user_urls, namespace='users')),
    url(r'^thoughts/', include(thought_urls, namespace='thoughts')),
    url(r'^groups/', include(group_urls, namespace='groups')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^api/', include(user_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

users/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^dashboard/$', views.Dashboard.as_view(), name='dashboard'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url('^', include('django.contrib.auth.urls')),
]

templates/index.html
{% extends "layout.html" %}

{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome to Kare!</h1>
        <p>Kare lets you track your feelings on different occasions and times.It can helps you to make a little bit more controle over your feelings and thoughts.With the help of Karey you can care yourself in more appropriate way in the context of your emations and feelings.For example on a specific oscasion you shouldn't be angry but you do unconciously, it will helps you track this feelings and think about it later.</p>
        <p><a class="btn btn-primary btn-lg cb" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2> Track </h2>
            <p> Track your feelings and emotions minute by minute.Track something is a best and easy way to make more control over it.So, by tracking your feelings you can make more control over them according to various situations.</p>
          <p><a class="btn btn-default cbs" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Graphs</h2>
            <p>All of your feelings will be represented in graphs from Ecstatic to Paranoid from Top to bottom respectively.In this way you can get a clear picture of your feelings on a specific occasion under a specific situation. </p>
          <p><a class="btn btn-default cbs" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Grouping</h2>
            <p>You can create, join and leave two types of groups Family and Company.Family will represnts all of your personal relations either belongs to your family or friends list.And Company will represents all of your work relations.</p>
          <p><a class="btn btn-default cbs" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
{% endblock  %}
    </div>

templates/layout.html
{% load static from staticfiles %}
{% load group_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block title %} Kare {% endblock %}</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  {% block css %}{% endblock %}
  <link rel="stylesheet" href="{% static 'css/kare.css' %}">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
    <style>
        .cn{
            background: darkslategray;
            color: white;
            font-size: larger;
        }
        .cb{
            background: darkslategray;
        }
        .cb:hover{
            background: slategray;
        }
        .cbs{
            background: darkslategray;
            color: white;
            font-size: larger;
            text-decoration: none;
        }
    </style>
</head>
<body>
    <div class="container">
    <nav class="navbar navbar-default navbar-inverse navbar-fixed-top cn">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <a class="navbar-brand" href="{% url 'home' %}"> &nbsp; &nbsp; <b>Kare</b> </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
            {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Companies {% invites_dot 'company' %}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for company in user.companies.all %}
                            <li><a href="{% url 'groups:companies:detail' slug=company.slug %}">{{ company.name }}</a></li>
                        {% endfor %}
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="{% url 'groups:companies:invites' %}">Invitations {% invites_badge 'company' %}</a>
                            <a href="{% url 'groups:companies:create' %}">Create New</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Families {% invites_dot 'family' %}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% for family in user.families.all %}
                            <li><a href="{% url 'groups:families:detail' slug=family.slug %}">{{ family.name }}</a></li>
                        {% endfor %}
                        <li role="separator" class="divider"></li>
                        <li>
                            <a href="{% url 'groups:families:invites' %}">Invitations {% invites_badge 'family' %}</a>
                            <a href="{% url 'groups:families:create' %}">Create New</a>
                        </li>
                    </ul>
                </li>
            </ul>
        {% endif %}
            <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
                <li><a href="{% url 'users:login' %}">Login</a></li>
                <li><a href="{% url 'users:signup' %}">Sign up</a></li>
            {% else %}
                <li><a href="{% url 'users:dashboard' %}">Dashboard</a></li>
                <li><a href="{% url 'users:logout' %}">Logout  &nbsp; &nbsp;</a></li>
            {% endif %}
            </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

    {% block content %}{% endblock %}

    <div class="container">
     <hr>

      <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</body>
</html>